dist: trusty
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm test
deploy:
  provider: npm
  email: novikovio74@gmail.com
  api_key:
    secure: L2Ew9y7XRoh2bQQ6YYJrQK/BudKNElPOeoqLzS6yLk7TqfcxXqlKMzQHQkbhxqoVNrdMa11mN0Qo4ew5whYUS9HAAQuCVsUjQn5tviAwRNuHE1Y9PeVKZytFAmcEfKiHSNIY52pmzahXwFEl7aksyeOOwBSumGd3M/fmscz/a5dQRD6xFLX2l81JL0gstZEqfEEnRbGq3UEOTnR11mGf4PiZW6QZZRiOBCsKTs870MwGeX487jBXuP/aJizyyTk30WY/rpY5TYlFQ/xCcu2JA6ev89XZIZ7jJwfx3tG+McM6szsgV3N+lCTVnav7X5Souz7ccnY9RI1eEmOKjb6+lgABVHOJqKD3jhU5e+zHhe985na0PdG0WBNqQqlkc/Eo1w28g5nMKPFWQdtLSZJIdu9ummR9xY7K4aq+4xHbfSommOb5Fovtl/0764CCt36B2Pyft/ZqYmjg9Tdicydvgf74nIXqfCNKPScrNbZNMoschNuQHWKlkYUSXhmme/qEbGR36B3jecNd3xHH1ticLWQazEK0E7e8Sm3Zxt6zUYP7us0C87xoAOE6aJm0A0PM/mg1IudxAZR4em1KXRUOTTxGhYcbvbF+jDqkAbDdOHNvC9RNDIEVWWqUQOwKy2gKQXKps+8TVzEzZJJWIyf9/tE/WFr40bWekPk2gEQYrWs=
  tag: next
  on:
    branch: master
    tags: true
    repo: Hooked74/single-purpose-emitter
